# Generated by Django 3.1.4 on 2020-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songhome', '0003_auto_20201214_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
