# Generated by Django 3.1.4 on 2020-12-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songhome', '0004_auto_20201214_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='related_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
