# Generated by Django 3.1.4 on 2020-12-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songhome', '0005_comment_related_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='default.mp3', upload_to='media/audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='media/images/'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='songhome.song')),
            ],
        ),
    ]
